package com.techempower.gemini.input.contract;

import com.techempower.gemini.input.Input;
import com.techempower.gemini.input.QueryValues;
import com.techempower.gemini.input.Values;
import com.techempower.gemini.input.validator.Validator;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Function;

/**
 * A field in a contract. Associated with zero or more validators.
 *
 * @author ajohnston
 */
public interface IContractField<T>
{
  /**
   * Adds a validator to the field.
   *
   * @param validator the validator to add
   */
  IContractField<T> addValidator(Validator validator);
  
  /**
   * @return the name of the field
   */
  String getName();
  
  /**
   * @return true if the field must be specified by the user
   */
  boolean isRequired();
  
  /**
   * Sets whether or not the field must be specified by the user. If true, a validator is automatically created when
   * needed.
   *
   * @param required whether or not the field is required
   */
  IContractField<T> setRequired(boolean required);
  
  /**
   * @return whether or not multiple values can be specified for the field.
   */
  boolean isMultivalued();
  
  /**
   * Sets whether or not multiple values may be specified for the field.
   *
   * @param multivalued whether or not multiple values may be specified for the field.
   */
  IContractField<T> setMultivalued(boolean multivalued);
  
  /**
   * Provides the validators generated by the settings applied to this field, such as required.
   *
   * @return the standard validators to apply
   */
  default List<Validator> getStandardValidators()
  {
    List<Validator> validators = new ArrayList<>();
    if (isRequired())
    {
      validators.add(new RequiredFieldValidator(this));
    }
    return validators;
  }
  
  /**
   * May return null if no validators required.
   *
   * @return all validators for this field
   */
  List<Validator> getValidators();
  
  /**
   * Sets the function used to extract a value from the query.
   */
  IContractField<T> setValueAccess(Function<ContractFieldValues, T> valueAccess);
  
  /**
   * Sets the function used to extract a value from the query. If no value is found (null), default value is provided
   * instead.
   *
   * @see #setDefaultValue(Object)
   */
  default IContractField<T> setValueAccess(Function<ContractFieldValues, T> valueAccess, T defaultValue)
  {
    setValueAccess(valueAccess);
    setDefaultValue(defaultValue);
    return this;
  }
  
  /**
   * Sets the default value to set the field to after processing if no value is provided (null)
   *
   * @param defaultValue
   */
  IContractField<T> setDefaultValue(T defaultValue);
  
  /**
   * @return the default value to set the field to after processing if no value is provided (null)
   */
  T getDefaultValue();
  
  /**
   * Sets the current value of the field to the default value. This is a convenience method to avoid having to specify
   * the same value twice.
   */
  default IContractField<T> setValueToDefault()
  {
    setValue(getDefaultValue());
    return this;
  }
  
  /**
   * Not to be used during validation.
   *
   * @return
   */
  T getValue();
  
  /**
   * To be used during validation. Gets the value for the field using the given input and its value access.
   *
   * @param input
   * @return
   */
  default T getValueFrom(Input input)
  {
    Function<ContractFieldValues, T> valueAccess = getValueAccess();
    if (valueAccess != null)
    {
      T value = valueAccess.apply(new ContractFieldValues(new QueryValues(input), this));
      if (value != null)
      {
        return value;
      }
      else
      {
        return getDefaultValue();
      }
    }
    return null;
  }

  IContractField<T> setValue(T value);
  
  default IContractField<T> setFrom(Values values)
  {
    {
      Function<ContractFieldValues, T> valueAccess = getValueAccess();
      if (valueAccess != null)
      {
        T value = valueAccess.apply(new ContractFieldValues(values, this));
        if (value != null)
        {
          setValue(value);
        }
        else
        {
          setValue(getDefaultValue());
        }
      }
    }
    return this;
  }
  
  Function<ContractFieldValues, T> getValueAccess();
}
